### ISSUE TITLE
To-Do-App Assignment

### ISSUE THREAD

**Issue by Claire-Crawford** [Claire-Crawford/To-Do-App#1]
Goal: Keep track of what tasks you have completed and what needs to be done.

- [x] Create a new folder / GitHub repo

- [x] Use Vue.JS / HTML5 for all functionality

- [x] Use Bootstrap for visual design

- [x] Allow a task to be added to your list

- [x] Allow a task to be removed from your list

- [x] Allow a task to be marked as complete

- [x] Allow all tasks to be removed from your list

- [x] Prevent empty tasks from being added to the list

- [x] Email me the repo link when you’re done
